const fs = require('fs');
let content = fs.readFileSync('/Users/takumi.ikeda/運動タイプ診断/fittness_type-main/types-data.js', 'utf8');

const script = 'const window = {};\n' + content + '\nmodule.exports = window.EXERCISE_V2_TYPES;';
fs.writeFileSync('temp_types.js', script);
const types = require('./temp_types.js');

if (types['SFVD'].unsuited_plans) {
  types['SFVD'].unsuited_plans.forEach(p => {
    if (p.short_title === '感情の伴わない記録') p.short_title = '細かなデータ管理';
  });
}
if (types['GFMC'].unsuited_plans) {
  types['GFMC'].unsuited_plans.forEach(p => {
    if (p.short_title === '個人競技') p.short_title = 'ストイックな個人競技';
  });
}
if (types['GFVC'].unsuited_plans) {
  types['GFVC'].unsuited_plans.forEach(p => {
    if (p.short_title === '個人競技') p.short_title = '競争を伴う個人競技';
    if (p.short_title === '一人きりのトレーニング') p.short_title = '孤独な作業空間';
    if (p.short_title === '匿名のクラス') p.short_title = '参加者の顔が見えないクラス';
  });
}
if (types['GFVD'].unsuited_plans) {
  types['GFVD'].unsuited_plans.forEach(p => {
    if (p.short_title === '感情の伴わない記録') p.short_title = '無機質なデータ管理';
  });
}
if (types['GPMD'].unsuited_plans) {
  types['GPMD'].unsuited_plans.forEach(p => {
    if (p.short_title === '一人きりのトレーニング') p.short_title = '個人完結の運動';
  });
}
if (types['GPVC'].unsuited_plans) {
  types['GPVC'].unsuited_plans.forEach(p => {
    if (p.short_title === '匿名のクラス') p.short_title = '誰とも関わらないクラス';
  });
}

const newContent = '/* Auto-generated by scripts/parse-07-to-types.mjs — do not edit by hand */\nwindow.EXERCISE_V2_TYPES = ' + JSON.stringify(types, null, 2) + ';\n';
fs.writeFileSync('/Users/takumi.ikeda/運動タイプ診断/fittness_type-main/types-data.js', newContent);
console.log("Fixed via object manipulation.");
