const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'types-data.js');
let content = fs.readFileSync(filePath, 'utf8');

const match = content.match(/window\.EXERCISE_V2_TYPES\s*=\s*(\{.*\});/s);
if (!match) {
  console.error("Could not find EXERCISE_V2_TYPES in types-data.js");
  process.exit(1);
}

let typesData = JSON.parse(match[1]);

// Update SPMC
typesData['SPMC'].suit_plans = [
  { title: "通勤・退勤時の1駅ウォーキング", body: "毎日の移動ルートに少しだけ歩く距離を足す活動です。既存の生活習慣に「隣接」させる設計がこのタイプには最も機能しやすく、強い意志力を使わずに「気づいたらやっている」状態を自然に作り出すことができます。" },
  { title: "毎朝の固定ルート散歩", body: "起床後、いつも同じ道を歩くルーティンです。毎回コースを考える手間や決断のコストを減らし、自動的に体が動く仕組みを作ることが、派手さよりも「今日もやれた」という静かな事実を好むこのタイプの継続を支えます。" },
  { title: "就寝前の5分間ストレッチ", body: "歯磨きやお風呂の後にセットで行う、ごく短い時間のストレッチです。特別な準備がいらず、1日を静かに締めくくれるこの活動は、低〜中強度で安定したリズムを刻みたいこのタイプの美学に深くフィットします。" },
  { title: "週末の決まった時間の水泳", body: "毎週同じ時間にプールへ行き、自分のペースで淡々と泳ぐ活動です。他者の都合に左右されず、水の中の孤独と反復のリズムを楽しめる環境が、一人で静かに継続することを好む特性を最大限に活かします。" },
  { title: "家事の合間の「ながら」運動", body: "料理中のかかと上げや、テレビを見ながらのスクワットなどです。日常動作の中に運動を溶け込ませることで無意識の反復を生み出し、「特別なこと」をせずに運動量を確保するこのタイプならではの賢い戦略です。" }
];

typesData['SPMC'].unsuited_plans = [
  { title: "毎回内容が変わる高強度ブートキャンプ", body: "予測不可能なメニューと激しい追い込みは、静かなルーティンと安定を好む性質と真っ向から衝突します。変化が多すぎる環境はペースを乱し、運動そのものを避ける原因になってしまいます。" },
  { title: "大会出場を目指す特別トレーニング", body: "「特別な日」に向けた非日常の活動やイベント依存型の目標設定は、日常の安定したリズムを崩す引き金になりやすいです。地味な継続に価値を見出すこのタイプにとって、一時的な熱狂はかえって負担になります。" },
  { title: "仲間と時間を合わせるチームスポーツ", body: "他人の都合でスケジュールが変わったり、ペースを合わせたりしなければならない環境は、一人で淡々と進めたいSPMCにとって大きなストレスです。外部の要因に左右される活動は安定した継続を阻害します。" },
  { title: "焦って追加する激しい筋トレ", body: "「これだけじゃ足りないのでは」という不安から急に高負荷なプログラムを追加すると、それが継続全体を崩す原因になりやすいです。強度の急激な変化は、このタイプの最大の強みである「継続性」を根底から壊してしまいます。" },
  { title: "SNSで進捗を報告し合う企画", body: "他者の目や評価が入る環境では、自分だけの静かな達成感が失われ、やらされる義務感に変わってしまいます。外部からの刺激や承認を必要としないため、報告の仕組みはノイズにしかなりません。" }
];

const newContent = `/* Auto-generated by scripts/parse-07-to-types.mjs — do not edit by hand */\nwindow.EXERCISE_V2_TYPES = ${JSON.stringify(typesData)};\n`;
fs.writeFileSync(filePath, newContent, 'utf8');
console.log("Updated SPMC in types-data.js");
