const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'types-data.js');
let content = fs.readFileSync(filePath, 'utf8');

const match = content.match(/window\.EXERCISE_V2_TYPES\s*=\s*(\{.*\});/s);
if (!match) {
  console.error("Could not find EXERCISE_V2_TYPES in types-data.js");
  process.exit(1);
}

let typesData = JSON.parse(match[1]);

// Update SPVC
typesData['SPVC'].suit_plans = [
  { title: "毎朝の固定ストレッチ", body: "起きる時間、やる順番、回数を完全に固定し、1日のスタートの儀式として組み込む活動です。決まった型を毎日正確に繰り返すことに独自の美学と充実感を見出すこのタイプにとって、最も確実で安心できる継続の形になります。" },
  { title: "同じ曜日の同じヨガレッスン", body: "毎週決まった時間に、同じインストラクターのレッスンを受けるスタイルです。環境や内容が固定されていることが精神的な安定を生み、「完璧にやり切った」という達成感を毎週確実に味わうことができます。" },
  { title: "固定ルートのウォーキング", body: "景色や距離が完全に予測できる同じ道を歩く活動です。変化がないことは退屈ではなく、むしろ動作の質の向上や内省に集中できるため、このタイプにとっては非常に心地よい時間となります。" },
  { title: "毎回同じ動画の自宅ピラティス", body: "お気に入りの同じ動画を繰り返し再生し、動きの精度や呼吸の深さを少しずつ高めていく活動です。反復の中に深い洗練を見出す感受性を持っているため、同じことの繰り返しが最高のフィットネスになります。" },
  { title: "週1回の固定時間スイミング", body: "毎週同じ曜日の同じ時間にプールへ行き、決まった距離を自分のペースで淡々と泳ぎ切る活動です。他者の介入がなく、自分だけの完璧なルーティンを守り抜ける環境が、強い満足感をもたらします。" }
];

typesData['SPVC'].unsuited_plans = [
  { title: "毎回コースが変わる自由なプログラム", body: "「今日は何をしようか」と毎回考えること自体がストレスになり、実行のハードルが極端に上がります。型が確立されていない柔軟すぎる設計は、このタイプのリズムを根本から乱してしまいます。" },
  { title: "大会やイベントなど特別な日の追い込み", body: "日常のルーティンから外れた非日常的な活動は、安定したペースを乱す原因になりやすいです。「特別なこと」を組み込もうとするほど、本来持っている強固な習慣の基盤がもろくなってしまいます。" },
  { title: "仲間の都合で予定が変わる集団活動", body: "自分のコントロール外で時間や場所が急に変更される環境は、このタイプが最も苦手とする状況です。完璧な計画が他者によって崩されると、「やった気がしない」という強い不満が残ります。" },
  { title: "複雑すぎるトレーニングメニュー", body: "メニューが多すぎたり複雑すぎたりすると、「完璧にこなせない日」ができやすくなります。一度ルーティンが崩れると「全部やり直したくなる」性質があるため、複雑さは挫折の直接的な引き金になります。" },
  { title: "思いつきで行くランダムなジム通い", body: "計画性なくその日の気分で動くことは、このタイプにとって「正しく運動した」という確かな達成感につながりません。型のない活動は、運動としての価値を著しく低く感じさせます。" }
];

const newContent = `/* Auto-generated by scripts/parse-07-to-types.mjs — do not edit by hand */\nwindow.EXERCISE_V2_TYPES = ${JSON.stringify(typesData)};\n`;
fs.writeFileSync(filePath, newContent, 'utf8');
console.log("Updated SPVC in types-data.js");
