const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'types-data.js');
let content = fs.readFileSync(filePath, 'utf8');

const match = content.match(/window\.EXERCISE_V2_TYPES\s*=\s*(\{.*\});/s);
if (!match) {
  console.error("Could not find EXERCISE_V2_TYPES in types-data.js");
  process.exit(1);
}

let typesData = JSON.parse(match[1]);

// Update SPMH
typesData['SPMH'].suit_plans = [
  { title: "タイムアタック・ランニング", body: "毎回同じコースを走り、1秒でもタイムを縮めることを目標にする活動です。スマートウォッチ等での記録管理が必須であり、「昨日の自分を超える」という明確な指標が存在することが、このタイプの最も強力なモチベーションになります。" },
  { title: "重量・回数管理の本格筋トレ", body: "ノートやアプリで毎回の挙上重量と回数を厳密に記録し、少しずつ負荷を上げていくトレーニングです。測定可能な記録と進捗の可視化が、一人での活動においても高い集中力と継続力を生み出します。" },
  { title: "距離とパワーを測るロードバイク", body: "サイクルコンピューターで走行距離やワット数を計測し、自分の成長を数値で確認しながら走る活動です。他者との比較ではなく、過去の自分のデータと向き合う環境が、このタイプの本領を発揮させます。" },
  { title: "体組成記録付きのボディメイク", body: "毎日同じ条件で体重や体脂肪率を測定し、食事と運動の成果をグラフ化して分析する活動です。数値が更新されていく実感が動力になるため、結果が目に見える形で蓄積される仕組みが不可欠です。" },
  { title: "獲得標高を記録する登山", body: "登った山の高さや難易度をアプリに記録し、次回のより高い目標へのステップとして活用する活動です。達成すべき明確なハードルと、それを乗り越えた記録が残ることが、次への挑戦意欲を掻き立てます。" }
];

typesData['SPMH'].unsuited_plans = [
  { title: "楽しさ重視のレクリエーション", body: "「ただ楽しければいい」という目的のない活動は、成長の実感が得られず、このタイプにとっては時間の無駄に感じてしまいます。数値で証明できない成果は、継続の根拠になり得ません。" },
  { title: "記録を取らないゆるい運動", body: "数値化されない活動は「やった証拠」が残らず、モチベーションの維持が極めて困難になります。測定があるからこそ全力を出せる特性があるため、記録のない運動はエンジンがかかりません。" },
  { title: "仲間のペースに合わせるグループ走", body: "自分の限界に挑戦したいのに、他人のペースに合わせて手加減しなければならない状況は大きなストレスになります。一人で己の記録と向き合う時間を邪魔される環境は最も避けるべきです。" },
  { title: "毎回内容が変わる自由なクラス", body: "比較対象となる「過去の自分」のデータが取れないため、成長の度合いが測れず不完全燃焼になります。同じ条件で測定し続けられないプログラムは、このタイプの強みを活かせません。" },
  { title: "目標のない散歩", body: "目的地も時間制限もない活動は、内なる高いエネルギーと向上心を持て余してしまい、運動としての満足感が著しく低くなります。「更新できる数字」がない活動はすぐに飽きてしまいます。" }
];

const newContent = `/* Auto-generated by scripts/parse-07-to-types.mjs — do not edit by hand */\nwindow.EXERCISE_V2_TYPES = ${JSON.stringify(typesData)};\n`;
fs.writeFileSync(filePath, newContent, 'utf8');
console.log("Updated SPMH in types-data.js");
