const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'types-data.js');
let content = fs.readFileSync(filePath, 'utf8');

const match = content.match(/window\.EXERCISE_V2_TYPES\s*=\s*(\{.*\});/s);
if (!match) {
  console.error("Could not find EXERCISE_V2_TYPES in types-data.js");
  process.exit(1);
}

let typesData = JSON.parse(match[1]);

// Update SFVC
typesData['SFVC'].suit_plans = [
  { title: "自然の中の瞑想ウォーク", body: "木々や風を感じながら、自分のペースでゆっくり歩く活動です。心が静かになる時間がそのまま運動になるため、「動いた後に気持ちが変わった」という体験を最も得やすく、内省的なこのタイプに深くフィットします。" },
  { title: "自宅でのリセットヨガ", body: "誰の目も気にせず、その日の体調や気分に合わせて体を伸ばす時間です。心と体の対話が目的であり、外からの刺激やプレッシャーがない安全な環境でこそ、このタイプは最も自然に体を動かすことができます。" },
  { title: "公園のぼーっと歩き", body: "目的地を決めず、疲れたらベンチで休むといった、運動というより「外の空気を吸う」延長の活動です。心が重いときでも「少しだけ外に出よう」と思えるハードルの低さが、無理のない継続を可能にします。" },
  { title: "就寝前のゆるストレッチ", body: "1日の終わりに、心身の緊張をほどくための5分間です。頑張らないこと、そして「今日も少しだけ自分を労わった」という静かな実感が、繊細な心を持つこのタイプにとって確かな継続の根拠になります。" },
  { title: "マイペースな温水プール", body: "タイムを気にせず、水の浮力に身を任せてゆっくり泳いだり歩いたりする活動です。水の中という外部の刺激を遮断できる環境が、心の波に左右されやすいこのタイプに深いリラックスと安心感をもたらします。" }
];

typesData['SFVC'].unsuited_plans = [
  { title: "大人数でのグループレッスン", body: "周りのペースや高いテンションに合わせようとして心が激しく消耗し、運動そのものが苦痛になってしまいます。一人の静かな時間を好むこのタイプにとって、他者のエネルギーが飛び交う空間は刺激が強すぎます。" },
  { title: "タイムや回数を競う運動", body: "競争やプレッシャーは心への大きな負荷となり、「動いた後に整う」という本来の目的から完全に遠ざかってしまいます。比較される環境に身を置くと、体がこわばり、運動への抵抗感ばかりが育ってしまいます。" },
  { title: "高強度の追い込み系エクササイズ", body: "心身への急激な負荷は、このタイプが持つ繊細なバランスを崩しやすく、ひどい疲労感だけを残します。強度が高くなるほど「しんどいもの」という認識が強まり、次から運動を避ける原因になります。" },
  { title: "「絶対に休まない」と決めた習慣化", body: "心が重い日にも義務感で動こうとすると、できない自分への自己嫌悪に陥りやすく長続きしません。心の状態と体が深く連動しているため、無理な強制はかえって長期的な継続を破壊してしまいます。" },
  { title: "賑やかで音楽が響くスポーツジム", body: "大音量の音楽や活気あふれる声など、外部からの刺激が強すぎる環境は、自分の内側の感覚に集中できず疲弊しやすくなります。フィットネスよりもセラピーを求めるこのタイプには、静けさが不可欠です。" }
];

const newContent = `/* Auto-generated by scripts/parse-07-to-types.mjs — do not edit by hand */\nwindow.EXERCISE_V2_TYPES = ${JSON.stringify(typesData)};\n`;
fs.writeFileSync(filePath, newContent, 'utf8');
console.log("Updated SFVC in types-data.js");
